---
title: "specifics_of_medical_data"
output: html_document
date: "2023-10-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(readxl)
library(tidyverse)
library(rstatix)
library(pROC)
library(gtsummary)
```


```{r}
trauma <- read_excel('trauma.xlsx', range = cell_cols("B:M"))
trauma %>% 
  summary()
```
```{r}
library(summarytools)

view(dfSummary(trauma, 
               plain.ascii = FALSE, 
               style = "grid"))
```

```{r}
trauma <- trauma %>% 
  mutate(id = as.factor(id),
         Sex = as.factor(Sex),
         Height = as.numeric(sub("\"", "", Height)),
         Death  = as.factor(Death))
trauma %>% 
  summary()
```
```{r}
view(dfSummary(trauma, 
               plain.ascii = FALSE, 
               style = "grid"))
```

```{r}

n_male <- trauma %>% 
  filter(Sex == 'Male') %>% 
  nrow()
Hb_low_male <- trauma %>% 
  filter(Sex == 'Male') %>% 
  filter(Hb <= 13.5) %>% 
  nrow()
n_female <- trauma %>% 
  filter(Sex == 'Female') %>% 
  nrow()
Hb_low_female <- trauma %>% 
  filter(Sex == 'Female') %>% 
  filter(Hb <= 12) %>% 
  nrow()

data.frame(n_male = n_male,
       p_male = round(Hb_low_male/n_male, 2),
       n_female = n_female,
       p_female = round(Hb_low_female/n_female, 2))
```

```{r}
trauma <- trauma %>% 
  mutate(BMI = (Weight / 2.2) / ((Height * 0.0254) ** 2))

mean(trauma$BMI)
```

```{r}
n <- trauma %>% 
  nrow()
n_obese <- trauma %>% 
  filter(BMI > 30) %>% 
  nrow()
round(n_obese / n, 4)
```

```{r}
library(pROC)
roc_curve_HB <- roc(Death ~ Hb, data=trauma, ci = T)
roc_curve_HB
```
```{r, fig.height=3, fig.width=3, dpi=300}
roc_curve_HB %>% 
  ggroc() +
  ggtitle(paste0('AUC = ', round(roc_curve_HB$auc, 2))) +
  theme_minimal()
```

```{r}
library(pROC)
roc_curve_GSC <- roc(Death ~ GSC, data=trauma, ci = T)
roc_curve_GSC
```

```{r, fig.height=3, fig.width=3, dpi=300}
roc_curve_GSC %>% 
  ggroc() +
  ggtitle(paste0('AUC = ', round(roc_curve_GSC$auc, 2))) +
  theme_minimal()
```

```{r}
roc_curve_GSC %>% coords(x = "best", best.method = "closest.topleft")
```
```{r}

trauma %>% names()

trauma %>% 
    select_if(is.numeric) %>% 
    pivot_longer(cols = !Death) %>% 
    group_by(name) %>% 
    summarise(AUC = roc(Death, value, ci = T)$ci[2] %>% round(3),
              AUC_LCL = roc(Death, value, ci = T)$ci[1] %>% round(3),
              AUC_UCL = roc(Death, value, ci = T)$ci[3] %>% round(3))

```

